#!/bin/bash
set -e

INSTALL_DIR="${INSTALL_DIR:-$HOME/bin}"
pushd "$INSTALL_DIR" > /dev/null
REAL_INSTALL_DIR="$(pwd -P)"
popd > /dev/null
GIT_GET_BIN="$REAL_INSTALL_DIR/git-get"

VERSION="$(git describe --tags)"
sed "s/%VERSION%/$VERSION/" git-get >"$GIT_GET_BIN"
chmod +x "$GIT_GET_BIN"

echo "git-get installed to $GIT_GET_BIN"
if [[ "$PATH" != *"$REAL_INSTALL_DIR"* ]]; then
  echo "Warning: $REAL_INSTALL_DIR not found in \$PATH"
  echo "
  Add the following to your shell profile:
    export PATH=\"$REAL_INSTALL_DIR:\$PATH\""
fi
