#!/usr/bin/env bash
set -e

main() {
  echo "==> Testing git-get"
  GIT_PATH="$(pwd)./test-repos"
  rm -rf $GIT_PATH
  mkdir -p $GIT_PATH
  cd "$(./git-get https://github.com/pietvanzoen/git-get.git)"

  assert_equal $(pwd) "$GIT_PATH/github.com/pietvanzoen/git-get" "sets correct repo path"
}


assert_equal () {
  if [[ "$1" != "$2" ]]; then
    echo "FAIL: $3"
    echo -e "  expected $2 \n  but got  $1"
    exit 1
  fi
  echo "PASS: $3"
}

main
